<?php

function custom_follow_follow_networks_alter(&$networks, $uid = 0){
  $networks[$uid]['etsy'] = array(
    'title' => t('Etsy'),
    'domain' => 'etsy.com',
  );

  $networks[$uid]['redbubble'] = array(
    'title' => t('Redbubble'),
    'domain' => 'redbubble.com',
  );

  $networks[$uid]['github'] = array(
    'title' => t('GitHub'),
    'domain' => 'github.com',
  );

  $networks[$uid]['imdb'] = array(
    'title' => t('IMDB'),
    'domain' => 'imdb.com',
  );
}
//add etsy
